### ISSUE TITLE
Re-instantiating using tree state can result in invalid model

### ISSUE THREAD

**Issue by bwzhang96** [aws/random-cut-forest-by-aws#148]
On compact-rcf branch, when mapping between state and model with saveTreeState enabled, sometimes the re-instantiated model will fail to update due to IllegalStateException

Example exception:
```
java.lang.IllegalStateException: [16.0, 28.0, 41.0, 13.0, 23.0, 24.0, 11.0, 34.0, 4.0, 18.0] [17.0, 26.0, 25.0, 13.0, 31.0, 4.0, 34.0, 11.0, 8.0, 15.0] 121 node false Inconsistency in trees in delete step here.

	at com.amazon.randomcutforest.tree.AbstractRandomCutTree.deletePoint(AbstractRandomCutTree.java:276)
	at com.amazon.randomcutforest.tree.AbstractRandomCutTree.deletePoint(AbstractRandomCutTree.java:315)
	at com.amazon.randomcutforest.tree.AbstractRandomCutTree.deletePoint(AbstractRandomCutTree.java:315)
	at com.amazon.randomcutforest.tree.AbstractRandomCutTree.deletePoint(AbstractRandomCutTree.java:315)
	at com.amazon.randomcutforest.tree.AbstractRandomCutTree.deletePoint(AbstractRandomCutTree.java:315)
	at com.amazon.randomcutforest.tree.AbstractRandomCutTree.deletePoint(AbstractRandomCutTree.java:315)
	at com.amazon.randomcutforest.tree.AbstractRandomCutTree.deletePoint(AbstractRandomCutTree.java:315)
	at com.amazon.randomcutforest.tree.AbstractRandomCutTree.deletePoint(AbstractRandomCutTree.java:315)
	at com.amazon.randomcutforest.tree.AbstractRandomCutTree.deletePoint(AbstractRandomCutTree.java:315)
	at com.amazon.randomcutforest.tree.AbstractRandomCutTree.deletePoint(AbstractRandomCutTree.java:255)
	at com.amazon.randomcutforest.executor.SamplerPlusTree.update(SamplerPlusTree.java:79)
``` 

The following code can demonstrate the issue. Unfortunately, it doesn't reproduce the issue 100% of the time. If I run it 100 times, I'll get a roughly 50/50 split of success/failure. I think this ultimately has to do with how points get evicted, but I don't fully understand the RCF algorithm to know why. Running the below test with saveTreeState disabled always results in success though.
```
    @Test
    public void reproduce() {
        int dimensions = 10;
        RandomCutForest forest = RandomCutForest.builder().compactEnabled(true).dimensions(dimensions)
           .sampleSize(64).precision(Precision.SINGLE).build();

        Random r = new Random();
        for (int i = 0; i < 30; i++) {
            forest.update(r.ints(dimensions, 0, 50).asDoubleStream().toArray());
        }

        // serialize + deserialize
        RandomCutForestMapper mapper = new RandomCutForestMapper();
        mapper.setSaveTreeState(true);
        mapper.setSaveExecutorContext(true);
        RandomCutForest forest2 = mapper.toModel(
            mapper.toState(forest)
        );

        // update re-instantiated forest
        for (int i = 0; i < 100; i++) {
            forest2.update(r.ints(dimensions, 0, 50).asDoubleStream().toArray());
        }
    }
```

**Comment by sudiptoguha** [comment]
Thank you for trying out the library and spotting this! The problem was that the bounding boxes are not saved during serialization (by design). At deserialization, we now only build this bounding boxes that are absolutely necessary (on demand). That logic was incorrect, and since bounding boxes were incorrect, addPoint was incorrect. Delete is actually a very simple operation in RCF, usually the culprit is almost always addPoint. Please let us know if the issue went away for you.

**Comment by jotok** [comment]
We believe this issue was caused by a bug in the bounding box logic. Working on a fix in #149

**Comment by jotok** [comment]
Closed by #149
