### ISSUE TITLE
Incomplete State 255 Error

### ISSUE THREAD

**Issue by amitgalitz** [aws/random-cut-forest-by-aws#328]
Steps to reproduce on RCF:
1. Convert following [model](https://github.com/amitgalitz/random-cut-forest-by-aws/blob/34376fe9b77ea2f0e5c1e55450c5c62a5a71f0ac/Java/parkservices/src/test/resources/com/amazon/randomcutforest/parkservices/state/state_3.json) in JSON format to trcf:  using following [unit test](https://github.com/aws/random-cut-forest-by-aws/blob/main/Java/parkservices/src/test/java/com/amazon/randomcutforest/parkservices/state/V2TRCFToV3StateConverterTest.java#L45):

Seed given: 4956439335943109988
Feature input: 88.0

2. Exception is thrown: 
```
java.lang.IllegalArgumentException:  incomplete state 255
 
	at com.amazon.randomcutforest.CommonUtils.checkArgument(CommonUtils.java:42)
	at com.amazon.randomcutforest.tree.AbstractNodeStore.growNodeBox(AbstractNodeStore.java:315)
	at com.amazon.randomcutforest.tree.AbstractNodeStore.growNodeBox(AbstractNodeStore.java:327)
	at com.amazon.randomcutforest.tree.RandomCutTree.addPoint(RandomCutTree.java:252)
	at com.amazon.randomcutforest.tree.RandomCutTree.addPoint(RandomCutTree.java:51)
	at com.amazon.randomcutforest.state.RandomCutForestMapper.lambda$singlePrecisionForest$1(RandomCutForestMapper.java:339)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
	at com.amazon.randomcutforest.state.RandomCutForestMapper.singlePrecisionForest(RandomCutForestMapper.java:339)
	at com.amazon.randomcutforest.state.RandomCutForestMapper.toModel(RandomCutForestMapper.java:231)
	at com.amazon.randomcutforest.state.RandomCutForestMapper.toModel(RandomCutForestMapper.java:55)
	at com.amazon.randomcutforest.state.IContextualStateMapper.toModel(IContextualStateMapper.java:24)
	at com.amazon.randomcutforest.state.RandomCutForestMapper.toModel(RandomCutForestMapper.java:299)
	at com.amazon.randomcutforest.parkservices.state.ThresholdedRandomCutForestMapper.toModel(ThresholdedRandomCutForestMapper.java:50)
	at com.amazon.randomcutforest.parkservices.state.ThresholdedRandomCutForestMapper.toModel(ThresholdedRandomCutForestMapper.java:38)
	at com.amazon.randomcutforest.state.IStateMapper.toModel(IStateMapper.java:24)
	at com.amazon.randomcutforest.parkservices.state.V2TRCFToV3StateConverterTest.testJson(V2TRCFToV3StateConverterTest.java:51)...
```

Steps to reproduce to get model from AD, Opensearch 2.0:
1. Load training data with 100 entities and create AD over it
2. print trcf model when exception is thrown on one of the entities
3. Deserialize model produced for the entity and there will be an incomplete State 255 error

**Comment by ylwu-amzn** [comment]
Fixed by this PR https://github.com/aws/random-cut-forest-by-aws/pull/329?

**Comment by amitgalitz** [comment]
Yes this has been fixed and tested with that PR.
