### ISSUE TITLE
Signed zero causes NullPointerException

### ISSUE THREAD

**Issue by kaituo** [aws/random-cut-forest-by-aws#47]
Running the unit test can reproduce the issue:

```
RandomCutForestFunctionalTest:

    // Use this ArgumentsProvider to run a test on both single-threaded and
    // multi-threaded forests
    static class TestForestProvider2 implements ArgumentsProvider {
        @Override
        public Stream<? extends Arguments> provideArguments(ExtensionContext context) throws Exception {
            RandomCutForest forest = RandomCutForest.builder().numberOfTrees(numberOfTrees).sampleSize(sampleSize)
                    .dimensions(1).randomSeed(randomSeed).centerOfMassEnabled(true)
                    .storeSequenceIndexesEnabled(true).parallelExecutionEnabled(false).build();
            return Stream.of(forest).map(Arguments::of);
        }
    }

    @ParameterizedTest
    @ArgumentsSource(TestForestProvider2.class)
    public void testSideEffectsC(RandomCutForest forest) {
        /* the changes to score and attribution should be in sync */
        forest.update(new double[] { 0.0 });
        forest.update(new double[] { -0.0 });
    }

```

NullPointerException will be thrown:

```
java.lang.NullPointerException: null
        at com.amazon.randomcutforest.tree.Cut.isLeftOf(Cut.java:52) ~[random-cut-forest-1.0.jar:?]
        at com.amazon.randomcutforest.tree.Node.isLeftOf(Node.java:134) ~[random-cut-forest-1.0.jar:?]
        at com.amazon.randomcutforest.tree.RandomCutTree.addPoint(RandomCutTree.java:348) ~[random-cut-forest-1.0.jar:?]
        at com.amazon.randomcutforest.tree.RandomCutTree.addPoint(RandomCutTree.java:349) ~[random-cut-forest-1.0.jar:?]
        at com.amazon.randomcutforest.tree.RandomCutTree.addPoint(RandomCutTree.java:349) ~[random-cut-forest-1.0.jar:?]
        at com.amazon.randomcutforest.tree.RandomCutTree.addPoint(RandomCutTree.java:349) ~[random-cut-forest-1.0.jar:?]
        at com.amazon.randomcutforest.tree.RandomCutTree.addPoint(RandomCutTree.java:349) ~[random-cut-forest-1.0.jar:?]
        at com.amazon.randomcutforest.tree.RandomCutTree.addPoint(RandomCutTree.java:349) ~[random-cut-forest-1.0.jar:?]
        at com.amazon.randomcutforest.tree.RandomCutTree.addPoint(RandomCutTree.java:349) ~[random-cut-forest-1.0.jar:?]
        at com.amazon.randomcutforest.tree.RandomCutTree.addPoint(RandomCutTree.java:349) ~[random-cut-forest-1.0.jar:?]
        at com.amazon.randomcutforest.tree.RandomCutTree.addPoint(RandomCutTree.java:349) ~[random-cut-forest-1.0.jar:?]
        at com.amazon.randomcutforest.tree.RandomCutTree.addPoint(RandomCutTree.java:349) ~[random-cut-forest-1.0.jar:?]
        at com.amazon.randomcutforest.tree.RandomCutTree.addPoint(RandomCutTree.java:272) ~[random-cut-forest-1.0.jar:?]
        at com.amazon.randomcutforest.TreeUpdater.update(TreeUpdater.java:82) ~[random-cut-forest-1.0.jar:?]
        at com.amazon.randomcutforest.SequentialForestTraversalExecutor.lambda$update$0(SequentialForestTraversalExecutor.java:38) ~[random-cut-forest-1.0.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1507) ~[?:?]
        at com.amazon.randomcutforest.SequentialForestTraversalExecutor.update(SequentialForestTraversalExecutor.java:37) ~[random-cut-forest-1.0.jar:?]
        at com.amazon.randomcutforest.AbstractForestTraversalExecutor.update(AbstractForestTraversalExecutor.java:50) ~[random-cut-forest-1.0.jar:?]
        at com.amazon.randomcutforest.RandomCutForest.update(RandomCutForest.java:291) ~[random-cut-forest-1.0.jar:?]
```

RCF does not consider new double[] { 0.0 } and new double[] { -0.0 } to be equal since it uses [Arrays.equals](https://github.com/aws/random-cut-forest-by-aws/blob/main/Java/core/src/main/java/com/amazon/randomcutforest/tree/Node.java#L229) to compare them.  But actually 0.0 == -0.0.  These arrays should be equal.  This causes RandomCutTree.addPoint to access [Node.isLeftOf](https://github.com/aws/random-cut-forest-by-aws/blob/main/Java/core/src/main/java/com/amazon/randomcutforest/tree/Cut.java#L53)  where cut is null.

**Comment by wnbts** [comment]
thanks for the report! as per [java doc](https://docs.oracle.com/javase/7/docs/api/java/util/Arrays.html#equals(double[],%20double[])) of Arrays::equals
>  Two doubles d1 and d2 are considered equal if:
>
>    new Double(d1).equals(new Double(d2))
>
>(Unlike the == operator, this method considers NaN equals to itself, and 0.0d unequal to -0.0d.)

The desired equality test in this library is element-wise == , which doesn't seem to match any built-in api. So a custom implementation and possibly a refactoring will be needed. If the plan sounds good, I can start making the changes.

**Comment by kaituo** [comment]
sounds good to me.

**Comment by wnbts** [comment]
An alternative is to add a data cleaning step (such as converting -0 to 0) before updating the model with it. This will make the code base much easier to develop on and maintain since it's less practicable to make every developer and maintainer of this code to defend such an issue everywhere with arrays, scalars, collections throughout the code. The general idea is to gate data into model upon entry once rather than letting it spread and then defending it in all parts, thereby lowering overall costs and complexity.

**Comment by jotok** [comment]
I like this idea. Currently a point is copied in the forest traversal executor ([here](https://github.com/aws/random-cut-forest-by-aws/blob/main/Java/core/src/main/java/com/amazon/randomcutforest/AbstractForestTraversalExecutor.java#L50)), and the same copied point is passed around by reference to use everywhere else. If we recode -0 to 0 in this one place, I think that will fix the issue.
